--
-- PostgreSQL database cluster dump
--

-- Started on 2025-04-22 23:17:06

SET default_transaction_read_only = off;

SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;

--
-- Roles
--

--CREATE ROLE postgres;
DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'postgres') THEN
        CREATE ROLE postgres;
    END IF;
END $$;
ALTER ROLE postgres WITH SUPERUSER INHERIT CREATEROLE CREATEDB LOGIN REPLICATION BYPASSRLS PASSWORD 'SCRAM-SHA-256$4096:RHGLPuHPZohkLL+Qpmuv0w==$9BHHE9Kpb8gEQKvzDxushUToLnR//Pqn5cn2Jj7zmJE=:La4zj3IavLT8Sd4oZx41Q2f2NH1aQbr+3H/A1hHnbws=';

--
-- User Configurations
--








--
-- Databases
--

--
-- Database "template1" dump
--

\connect template1

--
-- PostgreSQL database dump
--

-- Dumped from database version 17.2
-- Dumped by pg_dump version 17.2

-- Started on 2025-04-22 23:17:06

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

-- Completed on 2025-04-22 23:17:07

--
-- PostgreSQL database dump complete
--

--
-- Database "GoDB" dump
--

--
-- PostgreSQL database dump
--

-- Dumped from database version 17.2
-- Dumped by pg_dump version 17.2

-- Started on 2025-04-22 23:17:07

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 4845 (class 1262 OID 16395)
-- Name: GoDB; Type: DATABASE; Schema: -; Owner: postgres
--

--CREATE DATABASE "GoDB" WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE_PROVIDER = libc LOCALE = 'English_India.1252';
--
--
--ALTER DATABASE "GoDB" OWNER TO postgres;
--
--\connect "GoDB"

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 217 (class 1259 OID 16399)
-- Name: employee; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.employee (
    employeeid numeric(10,0),
    emailid character varying(20),
    name character varying(10),
    dateofbirth date,
    manufacturingunit character varying(10)
);


ALTER TABLE public.employee OWNER TO postgres;

--
-- TOC entry 4839 (class 0 OID 16399)
-- Dependencies: 217
-- Data for Name: employee; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.employee (employeeid, emailid, name, dateofbirth, manufacturingunit) FROM stdin;
2001	abc@gmail.com	abc	1998-05-15	U004
2007	wilson@mail.com	Wilson	1996-04-10	U001
2005	husee01@mail.com	h	1998-05-15	U005
\.


-- Completed on 2025-04-22 23:17:07

--
-- PostgreSQL database dump complete
--

--
-- Database "postgres" dump
--

\connect postgres

--
-- PostgreSQL database dump
--

-- Dumped from database version 17.2
-- Dumped by pg_dump version 17.2

-- Started on 2025-04-22 23:17:07

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 221 (class 1259 OID 24651)
-- Name: employee; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.employee (
    id bigint NOT NULL,
    department character varying(255),
    email character varying(255),
    job_title character varying(255),
    name character varying(255),
    salary numeric(38,2),
    user_id bigint
);


ALTER TABLE public.employee OWNER TO postgres;

--
-- TOC entry 220 (class 1259 OID 24650)
-- Name: employee_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.employee ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.employee_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 217 (class 1259 OID 16424)
-- Name: employee_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.employee_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.employee_seq OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 24659)
-- Name: leave_request; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.leave_request (
    id bigint NOT NULL,
    end_date date,
    reason character varying(255),
    start_date date,
    status character varying(255),
    employee_id bigint,
    CONSTRAINT leave_request_status_check CHECK (((status)::text = ANY ((ARRAY['Pending'::character varying, 'Approved'::character varying, 'Rejected'::character varying, 'Cancelled'::character varying])::text[])))
);


ALTER TABLE public.leave_request OWNER TO postgres;

--
-- TOC entry 222 (class 1259 OID 24658)
-- Name: leave_request_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.leave_request ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.leave_request_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 225 (class 1259 OID 24668)
-- Name: pay_roll; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.pay_roll (
    id bigint NOT NULL,
    basic_salary numeric(38,2),
    deductions numeric(38,2),
    net_salary numeric(38,2),
    pay_date date,
    employee_id bigint
);


ALTER TABLE public.pay_roll OWNER TO postgres;

--
-- TOC entry 224 (class 1259 OID 24667)
-- Name: pay_roll_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.pay_roll ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pay_roll_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 227 (class 1259 OID 24674)
-- Name: user_info; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.user_info (
    id bigint NOT NULL,
    email_id character varying(255),
    password character varying(255),
    role character varying(255),
    user_name character varying(255),
    CONSTRAINT user_info_role_check CHECK (((role)::text = ANY ((ARRAY['Admin'::character varying, 'HR'::character varying, 'Employee'::character varying])::text[])))
);


ALTER TABLE public.user_info OWNER TO postgres;

--
-- TOC entry 226 (class 1259 OID 24673)
-- Name: user_info_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.user_info ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_info_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 219 (class 1259 OID 16478)
-- Name: user_info_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.user_info_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.user_info_seq OWNER TO postgres;

--
-- TOC entry 218 (class 1259 OID 16425)
-- Name: user_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.user_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.user_seq OWNER TO postgres;

--
-- TOC entry 4883 (class 0 OID 24651)
-- Dependencies: 221
-- Data for Name: employee; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.employee (id, department, email, job_title, name, salary, user_id) FROM stdin;
1	IT	roja@gmail.com	Developer	Roja	90000.00	4
\.


--
-- TOC entry 4885 (class 0 OID 24659)
-- Dependencies: 223
-- Data for Name: leave_request; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.leave_request (id, end_date, reason, start_date, status, employee_id) FROM stdin;
1	2025-04-22	Vacation	2025-04-18	Approved	1
\.


--
-- TOC entry 4887 (class 0 OID 24668)
-- Dependencies: 225
-- Data for Name: pay_roll; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.pay_roll (id, basic_salary, deductions, net_salary, pay_date, employee_id) FROM stdin;
3	90000.00	5000.00	85000.00	2025-04-30	1
\.


--
-- TOC entry 4889 (class 0 OID 24674)
-- Dependencies: 227
-- Data for Name: user_info; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.user_info (id, email_id, password, role, user_name) FROM stdin;
4	roja@gmail.com	$2a$10$SobGl.bxdyypfXFCjYA0teHlGnDJ0gK5aW9ZeHi8J8KqN4LJA8Yji	Employee	Roja
5	ammu@gmail.com	$2a$10$MCPAU3ilY3RaZeQ7GX3MiOcuGd4/yPGD5LothLnmx8fqSsCTUMJBK	HR	Ammu
7	ganesh@gmail.com	$2a$10$N4H5VMEimRUZy1DU8SysXupUE53EPG7l7I6wxCqCiFVQKX4da7/Ze	Employee	Ganesh
10	janam.subu@gmail.com	$2a$10$MR/Cmvkv1VHZ2vEXkgvuSuheoMV/nqC52GgvqkNPRUkQqASPRcBXa	Admin	Jana
\.


--
-- TOC entry 4895 (class 0 OID 0)
-- Dependencies: 220
-- Name: employee_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.employee_id_seq', 1, true);


--
-- TOC entry 4896 (class 0 OID 0)
-- Dependencies: 217
-- Name: employee_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.employee_seq', 1, false);


--
-- TOC entry 4897 (class 0 OID 0)
-- Dependencies: 222
-- Name: leave_request_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.leave_request_id_seq', 1, true);


--
-- TOC entry 4898 (class 0 OID 0)
-- Dependencies: 224
-- Name: pay_roll_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.pay_roll_id_seq', 3, true);


--
-- TOC entry 4899 (class 0 OID 0)
-- Dependencies: 226
-- Name: user_info_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.user_info_id_seq', 10, true);


--
-- TOC entry 4900 (class 0 OID 0)
-- Dependencies: 219
-- Name: user_info_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.user_info_seq', 1, false);


--
-- TOC entry 4901 (class 0 OID 0)
-- Dependencies: 218
-- Name: user_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.user_seq', 1, false);


--
-- TOC entry 4716 (class 2606 OID 24657)
-- Name: employee employee_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employee
    ADD CONSTRAINT employee_pkey PRIMARY KEY (id);


--
-- TOC entry 4722 (class 2606 OID 24666)
-- Name: leave_request leave_request_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.leave_request
    ADD CONSTRAINT leave_request_pkey PRIMARY KEY (id);


--
-- TOC entry 4724 (class 2606 OID 24672)
-- Name: pay_roll pay_roll_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pay_roll
    ADD CONSTRAINT pay_roll_pkey PRIMARY KEY (id);


--
-- TOC entry 4726 (class 2606 OID 24687)
-- Name: pay_roll uk18h6xc9i2p9r1m7uhjwl9b2ti; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pay_roll
    ADD CONSTRAINT uk18h6xc9i2p9r1m7uhjwl9b2ti UNIQUE (employee_id);


--
-- TOC entry 4728 (class 2606 OID 24689)
-- Name: user_info ukeo44j61iq2l3i834bgn193qxr; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_info
    ADD CONSTRAINT ukeo44j61iq2l3i834bgn193qxr UNIQUE (email_id);


--
-- TOC entry 4718 (class 2606 OID 24683)
-- Name: employee ukfopic1oh5oln2khj8eat6ino0; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employee
    ADD CONSTRAINT ukfopic1oh5oln2khj8eat6ino0 UNIQUE (email);


--
-- TOC entry 4720 (class 2606 OID 24685)
-- Name: employee ukmpps3d3r9pdvyjx3iqixi96fi; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employee
    ADD CONSTRAINT ukmpps3d3r9pdvyjx3iqixi96fi UNIQUE (user_id);


--
-- TOC entry 4730 (class 2606 OID 24681)
-- Name: user_info user_info_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_info
    ADD CONSTRAINT user_info_pkey PRIMARY KEY (id);


--
-- TOC entry 4731 (class 2606 OID 24690)
-- Name: employee fk8rcy44mkkxm29111w6wd17mdi; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employee
    ADD CONSTRAINT fk8rcy44mkkxm29111w6wd17mdi FOREIGN KEY (user_id) REFERENCES public.user_info(id);


--
-- TOC entry 4733 (class 2606 OID 24700)
-- Name: pay_roll fkdypoa2dapbp3w1ythveynqjqa; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pay_roll
    ADD CONSTRAINT fkdypoa2dapbp3w1ythveynqjqa FOREIGN KEY (employee_id) REFERENCES public.employee(id);


--
-- TOC entry 4732 (class 2606 OID 24695)
-- Name: leave_request fktc4wao0ica39vusknbo96ln2w; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.leave_request
    ADD CONSTRAINT fktc4wao0ica39vusknbo96ln2w FOREIGN KEY (employee_id) REFERENCES public.employee(id);


-- Completed on 2025-04-22 23:17:08

--
-- PostgreSQL database dump complete
--

-- Completed on 2025-04-22 23:17:08

--
-- PostgreSQL database cluster dump complete
--

